[package]
name = "hilly-sounds"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0", optional = true }
clap = { version = "3.1", features = ["cargo", "derive"], optional = true }
cpal = { version = "0.13", features = ["jack"] }
derive_builder = "0.11"
dsp = "0.10"
hilbert = "0.1"
hound = "3.4"
nannou = "0.18"
nannou_egui = "0.5"
num-bigint = "0.4"

[[bin]]
name = "encode"
path = "src/bin/encode.rs"
required-features = ["binary"]

[[bin]]
name = "decode"
path = "src/bin/decode.rs"
required-features = ["binary"]

[features]
binary = ["anyhow", "clap"]