[package]
name = "hilly-sounds"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "3.1", features = ["cargo"] }
cpal = { version = "0.13", features = ["jack"] }
derive_builder = "0.11"
dsp = "0.10"
hilbert = "0.1"
hound = "3.4"
image = "0.24"
nannou = "0.18"
nannou_egui = "0.5"
num-bigint = "0.4"
# palette = "0.6"
rustfft = "6.0"

# TODO make many dependencies optional